version: '3.8'

services:
  aiyxdata_tradar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiyxdata_tradar
    ports:
      - "127.0.0.1:8084:8080"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
